
name: usage_docker_compose  
# version: '3.8'


services:

  mysql:
    # image: mysql:latest
    image: ghcr.io/u2waremanager/mysql:9.5.0
    # platform: linux/amd64
    container_name: usage_mysql
    environment:
      MYSQL_DATABASE : quest
      MYSQL_USER : quest
      MYSQL_PASSWORD : quest

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "3306:3306"

    volumes:
      - ./target/volumns/mysql:/var/lib/mysql


  postgres:
    image: ghcr.io/u2waremanager/postgres:16.4-alpine3.20
    platform: linux/amd64
    container_name: usage_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./target/volumns/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD : trust
      POSTGRES_DB: quest
      POSTGRES_USER: quest
      POSTGRES_PASSWORD: quest

  pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/amd64
    container_name: usage_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: usage_pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: usage_pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres

  app:
    image: usage_app:latest
    container_name: usage_app
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      # name: usage_app

    ports:
      - "8080:8080"
    environment:
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usage_database
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/usage_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: usage_password

      SPRING_JPA_DATABASE-PLATFORM : org.hibernate.dialect.MySQLDialect
      # SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT : org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update

    depends_on:
      postgres :
        condition: service_started
      mysql :
        condition: service_healthy
      # - postgres
      # - mysql
      # - pgadmin






